### ISSUE TITLE
would this work on ios  ?

### ISSUE THREAD

**Issue by weepy** [jmiskovic/hextrument#1]
?

**Comment by weepy** [comment]
awesome work BTW

**Comment by jmiskovic** [comment]
I don't have access to ios or mac, so I'm not able to do it, sorry.

The framework I use (LÖVE game) is available for iOS, so it _should_ be possible by [following instructions](https://love2d.org/wiki/Game_Distribution#iOS). I have no idea about audio latency and availability of realtime audio effects on iOS.

Anyway, I thought iOS has far better music instrument apps? I made this partly because I was impressed by Bebot Robot Synth and disappointed by existing Android apps.
