### ISSUE TITLE
Please add one column of buttons to the right

### ISSUE THREAD

**Issue by Ygarr** [jmiskovic/hextrument#11]
Please add ability to get one column of music notes on the right of keyboard. (If there is capability).While playin` theme from Mortal combat is hard to play part fast: "A E,  A C,  A A#,  A C, A A#-A-G"  
Fingering can be shifted to the left but other bars are played in this part, so just for convenience purposes
![Screenshot_20220717-015418_1](https://user-images.githubusercontent.com/14309871/179374881-f9ff63ba-4c13-46a0-9fbb-c2fa8091f262.png)

**Comment by jmiskovic** [comment]
Android screen sizes and aspect ratios can vary a lot. The application currently adapts the grid of notes to the screen size by picking a center note (E in this case) and adapting content to screen height so that it can fit two rows above and two rows below the center row. As for screen width, the current version app has fixed amount of columns it displays (11). For some aspect ratios this would result in empty unused sections at screen edges.

This will be fixed in the next version. Thank you for bringing this up.

**Comment by jmiskovic** [comment]
Fixed in v0.39.0.
