### ISSUE TITLE
Press twice to exit the app

### ISSUE THREAD

**Issue by jcperil** [jmiskovic/hextrument#16]
Kids accidentally close the app and then ask to bring up the app again. I mean it's annoying, their behavior. Can you please ask for confirmation before exiting the app? That would be a lot of help for unnecessary clicks.

Or you can block the navigation menu like [PianOli](https://github.com/nicolasbrailo/PianOli) does.

**Comment by jmiskovic** [comment]
The most common pattern seems to be double tap, with the "press again to exit" toast message. Since I want to avoid any text in the app, I'll disable exiting through BACK button and instead add a new icon just for closing the app.


![image](https://github.com/user-attachments/assets/3eeaa815-9f57-4cd8-95e4-9f8d4b2e5687)

**Comment by jmiskovic** [comment]
Added in v42
