### ISSUE TITLE
Goes silent when screen recorder is running

### ISSUE THREAD

**Issue by dharmatech** [jmiskovic/hextrument#18]
Wonderful app! Thank you for sharing it! 

It would be nice to use screen recorder to record the app live. However, when I use the standard screen recorder on a Samsung Ultra 22, hexpress stops making noise. I have to stop the recorder, stop hexpress, then restart hexpress to get the audio to work again.

**Comment by jmiskovic** [comment]
I was able to reproduce this issue. It only happens when the app was already running in background when the screen recorder is started.

This is unfortunate, but I am not able to fix the underlying issue. This would need to be addressed in the upstream framework love2d-android, or even it's upstream dependencies OpenAL and Oboe.

The easy workaround is to clear the app from recent app list before starting the recording. If the app has a chance to initialize the sound stack after the recording was started it would work. This obviously won't work if you already used the in-app tape to record something cool and now want to save it for later :(

BTW thanks for reporting this. I didn't know about it, a quick way to record stuff on the phone.

https://github.com/user-attachments/assets/f724c35f-9438-4721-82a8-dfd955e197d2

**Comment by dharmatech** [comment]
Thank you for the workaround of clearing it from the recent apps list! Works great! 👍
